import { DEFAULT_VALIDADE_DIAS } from './constants'
import type { Cliente, Orcamento, Profile } from '../types'

export const DEMO_PROFILE: Profile = {
  id: 'demo-user',
  nome: 'Equipe CKF',
  email: 'demo@ckfmanutencao.local',
  ativo: true,
  role: 'admin',
  criadoEm: new Date().toISOString(),
}

export const DEMO_CLIENTES: Cliente[] = [
  {
    id: 'cliente-demo-1',
    tipo: 'cnpj',
    nome: 'Condominio Centro Comercial',
    documento: '12345678000195',
    nomeFantasia: 'Centro Comercial',
    email: 'contato@centrocomercial.local',
    telefonePrincipal: '(47) 3333-4444',
    telefoneAlternativo: '',
    inscricaoEstadual: '',
    cep: '89010000',
    logradouro: 'Rua XV de Novembro',
    numero: '120',
    complemento: 'Administracao',
    bairro: 'Centro',
    cidade: 'Blumenau',
    uf: 'SC',
    referenciaAcesso: 'Entrada pela garagem de servico',
    observacoes: 'Cliente recorrente para manutencoes preventivas.',
    tags: ['condominio', 'recorrente'],
    ativo: true,
    criadoPor: DEMO_PROFILE.id,
    criadoPorNome: DEMO_PROFILE.nome,
    atualizadoPor: DEMO_PROFILE.id,
    criadoEm: '2026-05-14T09:00:00Z',
    atualizadoEm: '2026-05-14T09:00:00Z',
    representantes: [
      {
        id: 'rep-demo-1',
        clienteId: 'cliente-demo-1',
        nome: 'Marina Souza',
        cargo: 'Sindica',
        telefone: '(47) 99999-0000',
        email: 'marina@centrocomercial.local',
        observacao: 'Prefere contato no periodo da manha.',
        principal: true,
        ativo: true,
        criadoEm: '2026-05-14T09:00:00Z',
        atualizadoEm: '2026-05-14T09:00:00Z',
      },
    ],
  },
  {
    id: 'cliente-demo-2',
    tipo: 'cpf',
    nome: 'Carlos Roberto',
    documento: '11144477735',
    nomeFantasia: '',
    email: 'carlos.local@example.com',
    telefonePrincipal: '(47) 98888-7777',
    telefoneAlternativo: '',
    inscricaoEstadual: '',
    cep: '89030000',
    logradouro: 'Rua Bahia',
    numero: '640',
    complemento: '',
    bairro: 'Salto',
    cidade: 'Blumenau',
    uf: 'SC',
    referenciaAcesso: '',
    observacoes: '',
    tags: ['residencial'],
    ativo: true,
    criadoPor: DEMO_PROFILE.id,
    criadoPorNome: DEMO_PROFILE.nome,
    atualizadoPor: DEMO_PROFILE.id,
    criadoEm: '2026-05-15T09:00:00Z',
    atualizadoEm: '2026-05-15T09:00:00Z',
    representantes: [],
  },
]

export const DEMO_ORCAMENTOS: Orcamento[] = [
  {
    id: 'demo-1',
    numero: 285,
    dataOrcamento: '2026-05-16',
    servicoCliente: 'Filial São José',
    clienteId: 'cliente-demo-1',
    clienteNome: 'Condominio Centro Comercial',
    clienteDocumento: '12.345.678/0001-95',
    representanteId: 'rep-demo-1',
    representanteNome: 'Marina Souza',
    status: 'enviado',
    observacoes: 'Executar serviço em horário comercial.',
    validadeDias: DEFAULT_VALIDADE_DIAS,
    total: 500,
    criadoPor: DEMO_PROFILE.id,
    criadoPorNome: DEMO_PROFILE.nome,
    criadoEm: '2026-05-16T12:00:00Z',
    atualizadoEm: '2026-05-16T12:00:00Z',
    itens: [
      {
        id: 'demo-i1',
        quantidade: 2,
        descricao: 'Trocar parafusos quebrados, acabamento e pintura',
        valorUnitario: 250,
        valorTotal: 500,
      },
    ],
  },
  {
    id: 'demo-2',
    numero: 286,
    dataOrcamento: '2026-05-14',
    servicoCliente: 'Manutenção preventiva - Blumenau',
    clienteId: 'cliente-demo-2',
    clienteNome: 'Carlos Roberto',
    clienteDocumento: '111.444.777-35',
    representanteId: null,
    representanteNome: null,
    status: 'aprovado',
    observacoes: '',
    validadeDias: DEFAULT_VALIDADE_DIAS,
    total: 980,
    criadoPor: DEMO_PROFILE.id,
    criadoPorNome: DEMO_PROFILE.nome,
    criadoEm: '2026-05-14T13:00:00Z',
    atualizadoEm: '2026-05-15T09:00:00Z',
    itens: [
      {
        id: 'demo-i2',
        quantidade: 1,
        descricao: 'Revisão mecânica completa',
        valorUnitario: 980,
        valorTotal: 980,
      },
    ],
  },
]
